[package]
description = "Steam networking sockets IO layer implementation for aeronet"
name = "aeronet_steam"

authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
client = []
server = []

# so that this crate can still compile but be useless under WASM,
# we put the native-only dependencies under a `target` block
# but we still need `bevy_ecs` to be under the regular `dependencies`
# so that, when building for native, the `Component` macro realizes that
# it should use `::bevy_ecs` instead of `::bevy`
# (the macro reads the crate dependencies to figure out which to use)

[dependencies]
bevy_ecs = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
aeronet_io = { workspace = true }

thiserror = { workspace = true }
steamworks = { workspace = true }

bevy_app = { workspace = true }
bevy-steamworks = { workspace = true }

[dev-dependencies]
bevy = { workspace = true }
bevy_egui = { workspace = true }

[[example]]
name = "steam_client"
path = "examples/steam_client.rs"
required-features = ["client"]

[[example]]
name = "steam_echo_server"
path = "examples/steam_echo_server.rs"
required-features = ["server"]
