style_edition = "2024"

format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "One"
imports_granularity = "One"
newline_style = "Unix"
normalize_doc_attributes = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
