[package]
name = "aeronet_iroh"
version = "0.21.0"
edition.workspace = true
rust-version.workspace = true
description = "Iroh IO layer implementation for `aeronet`"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[[example]]
name = "iroh_peer"
path = "examples/iroh_peer.rs"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg=docsrs_aeronet"]
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[dependencies]
aeronet_io = { workspace = true }
bevy_app = { workspace = true }
bevy_ecs = { workspace = true }
bevy_platform = { workspace = true }
bytes = { workspace = true }
derive_more = { workspace = true, features = ["display", "error"] }
futures = { workspace = true }
iroh = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
bevy = { workspace = true }
clap = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = { workspace = true, features = ["rt-multi-thread"] }

[target.'cfg(target_family = "wasm")'.dependencies]
gloo-timers = { workspace = true, features = ["futures"] }
wasm-bindgen-futures = { workspace = true }

[lints]
workspace = true
