on:
  pull_request:
  push:
    branches:
      - main

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: crate-ci/typos@2a44449ff3410624a0fa2ea073c670e1c9236a40

  tombi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: tombi-toml/setup-tombi@9fdb1f12707aafdc140839c60421336d4ae157ea
        with:
          version: 1.2.6
      - run: tombi lint
      - run: tombi fmt --check
