[package]
edition = "2021"
name = "aeronet_proto_fuzz"
publish = false
version = "0.0.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

aeronet.path = "../../aeronet"
aeronet_proto.path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[profile.release]
debug = 1

[[bin]]
name = "msg_recv"
path = "fuzz_targets/msg_recv.rs"

doc = false
test = false

[[bin]]
name = "msg_send"
path = "fuzz_targets/msg_send.rs"

doc = false
test = false

[[bin]]
name = "session_recv"
path = "fuzz_targets/session_recv.rs"

doc = false
test = false
